changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature

    - title: 🐛 Bug Fixes
      labels:
        - bug

    - title: 📚 Documentation
      labels:
        - documentation

    - title: 🔒 Security
      labels:
        - security

    - title: ⚡ Performance
      labels:
        - performance

    - title: 🧪 Testing
      labels:
        - testing

    - title: 🔧 Maintenance
      labels:
        - maintenance

    - title: Other Changes
      labels:
        - "*"