name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Markdown Links
        uses: tcort/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes